#
# workflow
#
name: get json and push
on:
  push:
    branches:
      - "master"
      - "json-fetch"
  schedule:
    - cron: '2 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch-api
        env:
          apikey: ${{ secrets.API_KEY }}      
          userName: ${{ secrets.USER_NAME }}      
          userEmail: ${{ secrets.USER_EMAIL }}     
          branch: master 
        run: |
          baseurl=https://api.nhk.or.jp/v2/pg/list/
          mkdir -p json
          # set -x
          git fetch origin
          git checkout ./
          git checkout ${branch}
          git config --global user.name ${userName}
          git config --global user.email ${userEmail}
          bash kick_api.sh
          git add ./ 
          git commit -m "`date` add json"
          git push -f origin ${branch} 
